### ISSUE TITLE
`viewIf` can accidentally be used to make pages very slow!

### ISSUE THREAD

**Issue by brookeangel** [NoRedInk/elm-view-utils#3]
I did this 🐢  😢 

`viewIf : Html msg -> Bool -> Html msg`

The Html could be slow to calculate! Perhaps it should take a function instead so that the Html doesn't get calculated unless it should:

`viewIf : (() -> Html msg) -> Bool -> Html msg`

Doing this would help prevent people from accidentally making unnecessarily sloowwwww code 🐢  
In our case, we got a 4x speedup by using this fix! 🐎 

cc @avh4

**Comment by eeue56** [comment]
One of the issues with using `(() -> Html msg)` as a pattern is that it makes things very awkward to read. Elm-test currently suffers from this problem, where a standard test might look like this: `test "some thing" <| \_ -> Expect.banana`. A thunk-first approach to an API is pretty noisy as a result. I'd argue for "optimize as needed" in this case, and instead add some documentation about the alternative.

**Comment by stoeffel** [comment]
This has already changed in the latest version. I agree with Noah that it's a bit awkward, but at least we don't introduce performance issues by accident. I'll close for now, feel free to reopen if you think we still need to discuss this.
